class HaseError(Exception):
    pass


class PtError(Exception):
    pass
